matrix:
  include:
  - os: linux
    script:
    - ./create_firebase
annoy:
  provider: releases
  api_key:
    secure: W0NiAxk1KuJw/jxwyUlPZ2ri6GXCP0O0zfXpWxkvuIRFU0OiMjgv1Xp3mPmfqbjJMxlqaL/ExS+ZopUWYZGOmvP9alvHjbZXW7xX1VMFmPW8iCKbBZNBtx4+9GyPyCxN8h2B1xoSiUd7TstRA7CToZej8E1W77vCB33CAWowOKER2IPrVD5MKWmxlN37CABhsHyfUmNzxgl2NE1mrHrv4NE7BDVaDE3IZxrtNDAmgSZ2YjhO/hBWxTqo91FTAsPz/26fCpJsQJ4tQl/kp4U0SP0FdzAUdNKaABU2CJri/nMoOFFbqmwg71QFWFu4bma5rjRy9me5noygEuIXi9lo+1Jrsym4sBbYHm8Fti79Z/Gnv79WJDvAXtQA2olm7OcWM3nDTlh2GmfWUhAbWfinDT5VLIhJKcAvONF55FwT7Ab407J0IgQfUrmUzlgPw5HZ0x61ZqAkKcPmKbeMCZnYHzEY/uiMZvMHKqGS8qTYyr1tpC+OCl3Wb9HIzJjEOK2WP++MmwIy+Zu0ofAPsIqLzc0QpSko8LCjB0++oJgeZy7GD+Mv/wkVVfCnhJvqqio7LZrwMi94ZRassRKQw+gkbYlnenvTYGobcUR2r9fzxh0ObK6bh+wDqn70ydXPLeeiIKCEyqFCv+AaeLk+hz/as3kPCFodn1AdfoIOq7oe7RI=
  skip_cleanup: true
  true: 
    tags: true
  file: 
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/cdep-manifest-admob.yml
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/cdep-manifest-analytics.yml
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/cdep-manifest-app.yml
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/cdep-manifest-auth.yml
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/cdep-manifest-database.yml
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/cdep-manifest-invites.yml
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/cdep-manifest-messaging.yml
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/cdep-manifest-remote_config.yml
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/cdep-manifest-storage.yml
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-admob-c++.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-admob-gnustl.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-admob-stlport.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-analytics-c++.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-analytics-gnustl.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-analytics-stlport.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-app-c++.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-app-gnustl.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-app-stlport.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-auth-c++.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-auth-gnustl.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-auth-stlport.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-database-c++.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-database-gnustl.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-database-stlport.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-invites-c++.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-invites-gnustl.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-invites-stlport.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-messaging-c++.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-messaging-gnustl.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-messaging-stlport.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-remote_config-c++.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-remote_config-gnustl.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-remote_config-stlport.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-storage-c++.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-storage-gnustl.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-android-storage-stlport.zip
  - .deploy/com.jomofisher/firebase/${TRAVIS_TAG}/firebase-include.zip

